import { Command } from 'commander';
import { ConfigManager } from '../config/manager.js';
import { ProviderManager } from '../core/provider-manager.js';
import { FileManager } from '../integrations/file-manager.js';
import { Message, CommandContext } from '../types/index.js';
import { createCliKernel } from '../runtime/cli-kernel.js';
import { applyUnifiedDiff, extractUnifiedDiff } from '../utils/patch-utils.js';

const promptWithInquirer = async (questions: any[]) => (await import('inquirer')).default.prompt(questions);

export const editCommand = new Command('edit')
  .description('Edit files using AI assistance')
  .argument('<file>', 'File to edit')
  .requiredOption('-t, --task <task>', 'Description of the editing task')
  .option('-p, --provider <provider>', 'AI provider to use')
  .option('-m, --model <model>', 'Model to use')
  .option('--temperature <number>', 'Temperature (0-1)', parseFloat)
  .option('--max-tokens <number>', 'Max tokens', parseInt)
  .option('--preview', 'Show diff preview before applying')
  .option('--auto-apply', 'Apply changes without confirmation')
  .action(async (filePath, options) => {
    const configManager = new ConfigManager();
    const providerManager = new ProviderManager(configManager);
    const fileManager = new FileManager();
    
    try {
      const config = await configManager.getConfig();
      const context: CommandContext = {
        provider: options.provider || config.defaults.provider,
        model: options.model || config.defaults.model,
        temperature: options.temperature ?? config.defaults.temperature,
        maxTokens: options.maxTokens ?? config.defaults.maxTokens,
      };

      console.log(`📝 Editing ${filePath} with AI assistance...`);
      
      // Check if file exists
      if (!(await fileManager.fileExists(filePath))) {
        const { createFile } = await promptWithInquirer([
          {
            type: 'confirm',
            name: 'createFile',
            message: `File ${filePath} does not exist. Create it?`,
            default: true,
          },
        ]);

        if (!createFile) {
          console.log('❌ Operation cancelled.');
          return;
        }
      }

      // Read current file content
      let originalContent = '';
      try {
        if (await fileManager.fileExists(filePath)) {
          originalContent = await fileManager.readFile(filePath);
        }
      } catch (error) {
        console.error(`❌ Error reading file: ${error instanceof Error ? error.message : 'Unknown error'}`);
        return;
      }

      const fileExists = await fileManager.fileExists(filePath);
      const messages: Message[] = buildEditMessages(filePath, options.task, originalContent, fileExists);

      // Get AI response
      const provider = await providerManager.getProvider(context.provider!);
      const kernel = createCliKernel({
        provider,
        model: context.model,
        temperature: context.temperature,
        maxTokens: context.maxTokens,
        stateNamespace: 'cli',
      });
      
      console.log('🤖 Generating changes...');
      let modelResponse = '';
      
      const responseStream = provider.chat(messages, {
        model: context.model,
        temperature: context.temperature,
        maxTokens: context.maxTokens,
        stream: false,
      });

      for await (const chunk of responseStream) {
        modelResponse += chunk;
      }

      if (!modelResponse.trim()) {
        console.log('❌ No changes generated by AI.');
        return;
      }

      const editPlan = resolveEditPlan(filePath, originalContent, modelResponse, fileExists);
      if (!editPlan) {
        console.log('❌ The generated edit could not be parsed into a valid patch or file update.');
        return;
      }

      const diff = fileManager.createDiff(originalContent, editPlan.modifiedContent);
      
      if (diff.changes.length === 0) {
        console.log('ℹ️  No changes detected.');
        return;
      }

      // Show preview if requested or enabled by default
      if (options.preview || config.features.diffPreview) {
        console.log('\n📋 Change Preview:');
        console.log(fileManager.formatDiffPreview(diff));
      }

      // Get confirmation unless auto-apply is enabled
      let shouldApply = options.autoApply;
      
      if (!shouldApply) {
        const { apply } = await promptWithInquirer([
          {
            type: 'confirm',
            name: 'apply',
            message: `Apply ${diff.changes.length} changes to ${filePath}?`,
            default: true,
          },
        ]);
        shouldApply = apply;
      }

      if (shouldApply) {
        try {
          const session = await kernel.createSession(`Edit ${filePath}`, context.provider, context.model);
          if (fileExists) {
            await fileManager.backupFile(filePath);
          }

          const result = editPlan.kind === 'patch'
            ? await kernel.invokeTool(
                session.id,
                'apply_patch',
                {
                  path: filePath,
                  patch: editPlan.patch,
                },
                {
                  workspaceRoot: process.cwd(),
                }
              )
            : await kernel.invokeTool(
                session.id,
                'write_file',
                {
                  path: filePath,
                  content: editPlan.modifiedContent,
                },
                {
                  workspaceRoot: process.cwd(),
                }
              );

          if (!result.success) {
            throw new Error(result.error || 'Failed to write file');
          }
          console.log(`✅ Successfully applied changes to ${filePath}`);
          
          // Show backup location if file was backed up
          if (await fileManager.fileExists(filePath)) {
            console.log('💾 Original file backed up automatically');
          }
        } catch (error) {
          console.error(`❌ Error applying changes: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
      } else {
        console.log('❌ Changes not applied.');
      }
      
    } catch (error) {
      console.error('❌ Error:', error instanceof Error ? error.message : 'Unknown error');
    }
  });

function buildEditMessages(
  filePath: string,
  task: string,
  originalContent: string,
  fileExists: boolean
): Message[] {
  if (!fileExists) {
    return [
      {
        role: 'system',
        content: 'You are a professional code editor. Provide only the complete file content without explanations or markdown formatting.',
      },
      {
        role: 'user',
        content: `Create ${filePath} for this task:\n\n${task}\n\nReturn only the complete file content.`,
      },
    ];
  }

  return [
    {
      role: 'system',
      content: 'You are a professional code editor. Return only a valid unified diff patch for the target file. Do not include explanations.',
    },
    {
      role: 'user',
      content: `Edit ${filePath} for this task:\n\n${task}\n\nCurrent file content:\n\`\`\`\n${originalContent}\n\`\`\`\n\nReturn only a unified diff patch for ${filePath}. Use standard ---/+++ headers and @@ hunks.`,
    },
  ];
}

function resolveEditPlan(
  filePath: string,
  originalContent: string,
  modelResponse: string,
  fileExists: boolean
): { kind: 'patch'; patch: string; modifiedContent: string } | { kind: 'write'; modifiedContent: string } | null {
  if (!fileExists) {
    return {
      kind: 'write',
      modifiedContent: stripCodeFences(modelResponse),
    };
  }

  const patch = extractUnifiedDiff(modelResponse);
  if (!patch) {
    return null;
  }

  const modifiedContent = applyUnifiedDiff(originalContent, patch);
  if (modifiedContent === null) {
    return null;
  }

  return {
    kind: 'patch',
    patch,
    modifiedContent,
  };
}

function stripCodeFences(content: string): string {
  const trimmed = content.trim();
  const fencedMatch = trimmed.match(/```[a-z0-9_-]*\n([\s\S]*?)```/i);
  const fencedContent = fencedMatch?.[1];
  return fencedContent ? fencedContent.trim() : trimmed;
}
