import { Command } from 'commander';
import inquirer from 'inquirer';
import { ConfigManager } from '../config/manager.js';
import { ProviderManager } from '../core/provider-manager.js';
import { FileManager } from '../integrations/file-manager.js';
import { Message, CommandContext } from '../types/index.js';

export const editCommand = new Command('edit')
  .description('Edit files using AI assistance')
  .argument('<file>', 'File to edit')
  .requiredOption('-t, --task <task>', 'Description of the editing task')
  .option('-p, --provider <provider>', 'AI provider to use')
  .option('-m, --model <model>', 'Model to use')
  .option('--temperature <number>', 'Temperature (0-1)', parseFloat)
  .option('--max-tokens <number>', 'Max tokens', parseInt)
  .option('--preview', 'Show diff preview before applying')
  .option('--auto-apply', 'Apply changes without confirmation')
  .action(async (filePath, options) => {
    const configManager = new ConfigManager();
    const providerManager = new ProviderManager(configManager);
    const fileManager = new FileManager();
    
    try {
      const config = await configManager.getConfig();
      const context: CommandContext = {
        provider: options.provider || config.defaults.provider,
        model: options.model || config.defaults.model,
        temperature: options.temperature ?? config.defaults.temperature,
        maxTokens: options.maxTokens ?? config.defaults.maxTokens,
      };

      console.log(`📝 Editing ${filePath} with AI assistance...`);
      
      // Check if file exists
      if (!(await fileManager.fileExists(filePath))) {
        const { createFile } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'createFile',
            message: `File ${filePath} does not exist. Create it?`,
            default: true,
          },
        ]);

        if (!createFile) {
          console.log('❌ Operation cancelled.');
          return;
        }
      }

      // Read current file content
      let originalContent = '';
      try {
        if (await fileManager.fileExists(filePath)) {
          originalContent = await fileManager.readFile(filePath);
        }
      } catch (error) {
        console.error(`❌ Error reading file: ${error instanceof Error ? error.message : 'Unknown error'}`);
        return;
      }

      // Prepare AI prompt
      const prompt = `You are a professional code editor. Please help me with the following task:

Task: ${options.task}

Current file content (${filePath}):
\`\`\`
${originalContent}
\`\`\`

Please provide the complete modified file content. Include only the code, no explanations or markdown formatting.`;

      const messages: Message[] = [
        {
          role: 'system',
          content: 'You are a professional code editor. Provide only the complete modified file content without any explanations or markdown formatting.',
        },
        {
          role: 'user',
          content: prompt,
        },
      ];

      // Get AI response
      const provider = await providerManager.getProvider(context.provider!);
      
      console.log('🤖 Generating changes...');
      let modifiedContent = '';
      
      const responseStream = provider.chat(messages, {
        model: context.model,
        temperature: context.temperature,
        maxTokens: context.maxTokens,
        stream: false,
      });

      for await (const chunk of responseStream) {
        modifiedContent += chunk;
      }

      if (!modifiedContent.trim()) {
        console.log('❌ No changes generated by AI.');
        return;
      }

      // Create diff
      const diff = fileManager.createDiff(originalContent, modifiedContent);
      
      if (diff.changes.length === 0) {
        console.log('ℹ️  No changes detected.');
        return;
      }

      // Show preview if requested or enabled by default
      if (options.preview || config.features.diffPreview) {
        console.log('\n📋 Change Preview:');
        console.log(fileManager.formatDiffPreview(diff));
      }

      // Get confirmation unless auto-apply is enabled
      let shouldApply = options.autoApply;
      
      if (!shouldApply) {
        const { apply } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'apply',
            message: `Apply ${diff.changes.length} changes to ${filePath}?`,
            default: true,
          },
        ]);
        shouldApply = apply;
      }

      if (shouldApply) {
        try {
          await fileManager.applyDiff(filePath, diff);
          console.log(`✅ Successfully applied changes to ${filePath}`);
          
          // Show backup location if file was backed up
          if (await fileManager.fileExists(filePath)) {
            console.log('💾 Original file backed up automatically');
          }
        } catch (error) {
          console.error(`❌ Error applying changes: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
      } else {
        console.log('❌ Changes not applied.');
      }
      
    } catch (error) {
      console.error('❌ Error:', error instanceof Error ? error.message : 'Unknown error');
    }
  });